In [1]:
import torch

x = torch.ones(5)
y = torch.zeros(3)
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w) + b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

In [2]:
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

Gradient function for z = <AddBackward0 object at 0x7fafb4ae87f0>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x7fafb4ae8670>


Computing Gradients

In [3]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.0123, 0.1066, 0.0001],
        [0.0123, 0.1066, 0.0001],
        [0.0123, 0.1066, 0.0001],
        [0.0123, 0.1066, 0.0001],
        [0.0123, 0.1066, 0.0001]])
tensor([0.0123, 0.1066, 0.0001])


In [4]:
z = torch.matmul(x, w) + b
print(z.requires_grad)

with torch.no_grad():
    z = torch.matmul(x, w) + b
print(z.requires_grad)

True
False


In [7]:
z = torch.matmul(x, w) + b
z_det = z.detach()
print(z_det.requires_grad)

False


In [155]:
inp = torch.ones(1, requires_grad=True)
out = (inp+5).pow(2)
out.backward(torch.tensor([12]), retain_graph=True)
print(f"out\n{out}")
print(f"inp\n{inp}")
print(f"Grad\n{inp.grad}")

out
tensor([36.], grad_fn=<PowBackward0>)
inp
tensor([1.], requires_grad=True)
Grad
tensor([144.])


In [147]:
out

tensor([36.], grad_fn=<PowBackward0>)

In [148]:
inp

tensor([1.], requires_grad=True)

In [149]:
torch.ones_like(out)

tensor([1.])